import test from 'node:test';import assert from 'node:assert/strict';
import {newDocument,normalizeDocument,makeObject,makeStore,addItems,inventory,setPlaced,updateObject,deleteObject,footprint} from '../shared/planner-model.mjs';
test('legacy numeric IDs and commerce metadata survive roundtrip',()=>{const d=newDocument();d.objects=[makeObject('desk',{id:5,ownership:'owned'})];const v=normalizeDocument(JSON.parse(JSON.stringify(d)));assert.equal(v.objects[0].id,5);assert.equal(v.objects[0].placed,true);});
test('ten boxes are ten individually-sized inventory entries',()=>{const d=newDocument();addItems(d,'box',10,{w:60,d:45,h:38});assert.deepEqual(inventory(d),{total:10,placed:0,unplaced:10,boxes:10,owned:10,planned:0});assert.equal(d.objects[9].w,60);setPlaced(d,d.objects[0].id,true);assert.equal(inventory(d).unplaced,9);assert.equal(new Set(d.objects.map(o=>o.id)).size,10);});
test('unplacing never deletes owned items',()=>{const d=newDocument();const [o]=addItems(d,'chair',1,{placed:true});setPlaced(d,o.id,false);assert.equal(d.objects.length,1);assert.equal(d.objects[0].ownership,'owned');});
test('transactional undo/redo and invalid mutation rollback',()=>{const s=makeStore(newDocument());s.edit(d=>addItems(d,'desk'));assert.equal(s.get().objects.length,1);s.undo();assert.equal(s.get().objects.length,0);s.redo();assert.equal(s.get().objects.length,1);assert.throws(()=>s.edit(d=>d.room.w=-1));assert.equal(s.get().room.w,400);});
test('moving/rotating a parent carries its children',()=>{const d=newDocument();d.objects=[makeObject('desk',{id:'d',x:100,z:100}),makeObject('monitor',{id:'m',x:120,z:100,e:74,parent:'d'})];updateObject(d,'d',{x:200,r:90});assert.equal(d.objects[1].x,200);assert.equal(d.objects[1].z,120);assert.equal(d.objects[1].r,90);deleteObject(d,'d');assert.equal(d.objects[0].placed,false);});
test('reject malformed imported documents and parent cycles',()=>{const d=newDocument();d.objects=[makeObject('box',{id:'a',parent:'b'}),makeObject('box',{id:'b',parent:'a'})];assert.throws(()=>normalizeDocument(d));assert.throws(()=>normalizeDocument({...d,objects:[makeObject('box',{w:NaN})]}));assert.throws(()=>normalizeDocument({...d,objects:[makeObject('box',{id:1}),makeObject('box',{id:'1'})]}));});
test('catalog limit, decimal dimensions and L footprint are preserved',()=>{const d=newDocument();for(let i=0;i<5;i++)addItems(d,'box',50);assert.throws(()=>addItems(d,'box',1));assert.equal(footprint(makeObject('ldesk')).length,6);assert.equal(normalizeDocument({...d,objects:[makeObject('desk',{w:165.5})]}).objects[0].w,165.5);});

test('window migration respects explicit floor-level windows',()=>{const doc=newDocument();const win=makeObject('window',{x:200,z:0});delete win.e;doc.objects.push(win);assert.equal(normalizeDocument(doc).objects[0].e,88);win.e=0;assert.equal(normalizeDocument(doc).objects[0].e,0);win.e=2000;assert.throws(()=>normalizeDocument(doc));});
test('legacy numeric parent IDs normalize and all descendants survive deletion as unplaced',()=>{const d=newDocument();const a=makeObject('desk',{id:1}),b=makeObject('shelf',{id:2,parent:'1'}),c=makeObject('box',{id:3,parent:2});d.objects.push(a,b,c);const p=normalizeDocument(d);assert.equal(p.objects[1].parent,1);deleteObject(p,1);assert.equal(p.objects.length,2);assert.ok(p.objects.every(o=>!o.placed));});
