import {clone,normalizeDocument,inventory,uid,number} from './planner-model.mjs';
export const MAX_LAYOUTS=8;
export function safeView(v={}){const finite=(n,d,a,b)=>number(n,a,b)?n:d;return{mode:['2d','3d'].includes(v.mode)?v.mode:'2d',theta:finite(v.theta,-.55,-100,100),phi:finite(v.phi,.7,.02,1.5),scale:finite(v.scale,800,80,8000),target:Array.isArray(v.target)&&v.target.length===3&&v.target.every(n=>number(n,-5000,7000))?[...v.target]:[200,30,275],projection:v.projection==='perspective'?'perspective':'orthographic',eye:Array.isArray(v.eye)&&v.eye.length===3&&v.eye.every(n=>number(n,-5000,7000))?[...v.eye]:[200,150,520],style:['soft','sketch','clay'].includes(v.style)?v.style:'soft',cut:v.cut!==false};}
export function saveLayout(layouts,doc,name,view){if(layouts.length>=MAX_LAYOUTS)throw Error('배치안은 8개까지 저장할 수 있습니다.');return [...layouts,{id:uid(),name:String(name||`배치 ${layouts.length+1}`).slice(0,60),savedAt:new Date().toISOString(),document:normalizeDocument(clone(doc)),view:safeView(view)}];}
export function normalizeLayouts(items,projectId){if(!Array.isArray(items))return [];if(items.length>MAX_LAYOUTS)throw Error('배치안은 8개까지 불러올 수 있습니다.');const ids=new Set();return items.map(x=>{if(!x||!x.document)throw Error('배치안 데이터가 올바르지 않습니다.');const doc=normalizeDocument(x.document);if(doc.id!==projectId)throw Error('다른 프로젝트의 배치안이 섞여 있습니다.');const id=typeof x.id==='string'?x.id.slice(0,80):uid();if(ids.has(id))throw Error('배치안 ID가 중복됩니다.');ids.add(id);return{id,name:String(x.name||'배치안').slice(0,60),savedAt:String(x.savedAt||'').slice(0,40),document:doc,view:safeView(x.view)};});}
export function exportWorkspace(doc,layouts,view){return {...normalizeDocument(doc),workspace:{version:1,layouts:normalizeLayouts(layouts,doc.id),view:safeView(view)}};}
export function importWorkspace(value){if(typeof value==='string'){if(new TextEncoder().encode(value).length>4_000_000)throw Error('파일은 4MB 이하로 저장해 주세요.');value=JSON.parse(value);}const doc=normalizeDocument(value);return{doc,layouts:normalizeLayouts(value.workspace?.layouts||[],doc.id),view:safeView(value.workspace?.view)};}
export function compareLayouts(a,b){const left=new Map(a.objects.map(o=>[String(o.id),o])),right=new Map(b.objects.map(o=>[String(o.id),o]));let moved=0,resized=0,status=0;for(const [id,o]of left){const p=right.get(id);if(!p)continue;if(['x','z','r','e'].some(k=>Math.abs((o[k]||0)-(p[k]||0))>.01))moved++;if(['w','d','h'].some(k=>o[k]!==p[k]))resized++;if(o.placed!==p.placed||o.ownership!==p.ownership)status++;}return{added:[...right.keys()].filter(id=>!left.has(id)).length,removed:[...left.keys()].filter(id=>!right.has(id)).length,moved,resized,status,structureChanged:JSON.stringify(a.room)!==JSON.stringify(b.room),a:inventory(a),b:inventory(b)};}
export function commonView(a,b,view={}){const v=safeView(view),w=Math.max(a.room.w,b.room.w),d=Math.max(a.room.d,b.room.d);return{...v,mode:'3d',projection:'orthographic',target:[w/2,35,d/2],scale:Math.max(w,d)*1.65};}
